const CONSTANT = {
  REQUEST_MOVIE_DETAIL: 'REQUEST_MOVIE_DETAIL',
  REQUEST_MOVIE_DETAIL_ERROR: 'REQUEST_MOVIE_DETAIL_ERROR',
  REQUEST_MOVIE_DETAIL_SUCCESS: 'REQUEST_MOVIE_DETAIL_SUCCESS',

  REQUEST_MOVIE_CAST: 'REQUEST_MOVIE_CAST',
  REQUEST_MOVIE_CAST_ERROR: 'REQUEST_MOVIE_CAST_ERROR',
  REQUEST_MOVIE_CAST_SUCCESS: 'REQUEST_MOVIE_CAST_SUCCESS',


  REQUEST_SIMILAR_MOVIE: 'REQUEST_SIMILAR_MOVIE',
  REQUEST_SIMILAR_MOVIE_ERROR: 'REQUEST_SIMILAR_MOVIE_ERROR',
  REQUEST_SIMILAR_MOVIE_SUCCESS: 'REQUEST_SIMILAR_MOVIE_SUCCESS',
};

export default CONSTANT;
