const CONSTANT = {
  REQUEST_MOVIE_DETAIL: 'REQUEST_MOVIE_DETAIL',
  REQUEST_MOVIE_DETAIL_ERROR: 'REQUEST_MOVIE_DETAIL_ERROR',
  REQUEST_MOVIE_DETAIL_SUCCESS: 'REQUEST_MOVIE_DETAIL_SUCCESS',
};

export default CONSTANT;
