const CONSTANT = {
  REQUEST_NOW_PLAYING: 'REQUEST_NOW_PLAYING',
  REQUEST_NOW_PLAYING_ERROR: 'REQUEST_NOW_PLAYING_ERROR',
  REQUEST_NOW_PLAYING_SUCCESS: 'REQUEST_NOW_PLAYING_SUCCESS',
};

export default CONSTANT;
